# fly.toml app configuration file generated for map-app-2024-11-10 on 2024-11-10T16:29:36+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'map-app-2024-11-10'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
